# Data Preprocessing to Save & Load Model - Classification-Task
Keras is a deep learning API written in Python, running on top of the machine learning platform TensorFlow.
* Keras API documentation, visit: https://keras.io/api/

## Step-1: Data Preparation and Processing

In [4]:
import numpy as np
from sklearn.utils import shuffle
from sklearn.preprocessing import MinMaxScaler

### Create fake-dataset

In [5]:
train_labels = []
train_samples = []

Background of Example data:
    * An experiemental drug was tested on indivisuals from ages 13 to 100 in a clinical trail.
    * The trail had 2100 participants. half were 65 years or older.
    * 95% of patients 65 or older experienced side effects.
    * 95% of patients under 65 experienced no side effects.
    
Task: Create a model that can predict a new patient who may or may not experience any side effects.

In [6]:
# Creating Dataset
for i in range(50):
    #The 5% of younger individuals who did experience side effects.
    #Random ages 13~65 years
    random_younger = np.random.randint(13, 64)
    train_samples.append(random_younger)
    train_labels.append(1)
    
    # The 5% of older individuals who did not experience side effects.
    #Random ages 65~100 years
    random_older = np.random.randint(65, 100)
    train_samples.append(random_older)
    train_labels.append(0)

for i in range(1000):
    #The 5% of younger individuals who didnot experience side effects.
    #Random ages 13~65 years
    random_younger = np.random.randint(13, 64)
    train_samples.append(random_younger)
    train_labels.append(0)
    
    # The 5% of older individuals who did experience side effects.
    #Random ages 65~100 years
    random_older = np.random.randint(65, 100)
    train_samples.append(random_older)
    train_labels.append(1)

In [8]:
#first 10 samples
train_samples[:10]

[60, 71, 48, 93, 17, 90, 26, 95, 20, 99]

In [9]:
#first 10 labels
train_labels[:10]

[1, 0, 1, 0, 1, 0, 1, 0, 1, 0]

In [13]:
#shuffles the data
train_labels = np.array(train_labels)
train_samples = np.array(train_samples)
train_labels, train_samples = shuffle(train_labels, train_samples)

### Preprocessing data with MinMaxScaler

In [16]:
scaler = MinMaxScaler(feature_range=(0,1))
scaled_train_samples = scaler.fit_transform(train_samples.reshape(-1,1))

In [19]:
#first 10 samples
scaled_train_samples[:10]

array([[0.8255814 ],
       [0.39534884],
       [0.65116279],
       [0.76744186],
       [0.06976744],
       [0.06976744],
       [0.20930233],
       [0.90697674],
       [0.90697674],
       [0.8372093 ]])

## Step-2: Create an Artificial Neural Network(ANN) with Keras

### Import libraries

In [22]:
import keras
from keras import backend as k
from keras.models import Sequential
from keras.layers import Activation
from keras.layers.core import Dense
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy

In [27]:
model = Sequential([
    Dense(16, input_shape=(1,), activation='relu'),
    Dense(32, activation='relu'),
    Dense(2, activation='softmax')
])

In [25]:
#Add layers in another way
'''
model.add(Dense(16, input_shape=(1,), activation='relu'))
model.add(Dense(32, activation='relu'))
model.add(Dense(2, activation='softmax'))
'''

In [32]:
#Show the model architecture
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_3 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_4 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


## Step-3: Train the Artificial Neural Network or the Model

### Compile the model

In [33]:
model.compile(optimizer = Adam(learning_rate=0.0001), 
              loss = 'sparse_categorical_crossentropy', 
              metrics = ['accuracy'])

### fit the model with training dataset

In [39]:
model.fit(x=scaled_train_samples, y=train_labels, 
          batch_size=10, epochs=20, shuffle=True, verbose=2)

Epoch 1/20
 - 0s - loss: 0.2369 - accuracy: 0.9410
Epoch 2/20
 - 0s - loss: 0.2367 - accuracy: 0.9433
Epoch 3/20
 - 0s - loss: 0.2364 - accuracy: 0.9433
Epoch 4/20
 - 0s - loss: 0.2362 - accuracy: 0.9433
Epoch 5/20
 - 0s - loss: 0.2358 - accuracy: 0.9433
Epoch 6/20
 - 0s - loss: 0.2356 - accuracy: 0.9433
Epoch 7/20
 - 0s - loss: 0.2354 - accuracy: 0.9433
Epoch 8/20
 - 0s - loss: 0.2353 - accuracy: 0.9433
Epoch 9/20
 - 0s - loss: 0.2351 - accuracy: 0.9433
Epoch 10/20
 - 0s - loss: 0.2348 - accuracy: 0.9433
Epoch 11/20
 - 0s - loss: 0.2346 - accuracy: 0.9433
Epoch 12/20
 - 0s - loss: 0.2343 - accuracy: 0.9433
Epoch 13/20
 - 0s - loss: 0.2342 - accuracy: 0.9443
Epoch 14/20
 - 0s - loss: 0.2340 - accuracy: 0.9433
Epoch 15/20
 - 0s - loss: 0.2337 - accuracy: 0.9433
Epoch 16/20
 - 0s - loss: 0.2335 - accuracy: 0.9433
Epoch 17/20
 - 0s - loss: 0.2333 - accuracy: 0.9433
Epoch 18/20
 - 0s - loss: 0.2331 - accuracy: 0.9462
Epoch 19/20
 - 0s - loss: 0.2330 - accuracy: 0.9433
Epoch 20/20
 - 0s - l

## Step-4: Build a validation set

**validation_split = 0.1**
    * 10% of training data that is not going to train.

### Fit model with validation set
**It will show that the model is occurring Overfiting or Not**
* Total data 2100,
* Train on 1890 samples, validate on 210 samples
* Additional information,
    * val_loss
    * val_accuracy

In [42]:
model.fit(x=scaled_train_samples, y=train_labels, 
          batch_size=10, validation_split=0.1, epochs=20, shuffle=True, verbose=2)

Train on 1890 samples, validate on 210 samples
Epoch 1/20
 - 2s - loss: 0.2404 - accuracy: 0.9418 - val_loss: 0.1632 - val_accuracy: 0.9619
Epoch 2/20
 - 0s - loss: 0.2401 - accuracy: 0.9423 - val_loss: 0.1634 - val_accuracy: 0.9619
Epoch 3/20
 - 0s - loss: 0.2399 - accuracy: 0.9429 - val_loss: 0.1634 - val_accuracy: 0.9619
Epoch 4/20
 - 0s - loss: 0.2399 - accuracy: 0.9429 - val_loss: 0.1627 - val_accuracy: 0.9619
Epoch 5/20
 - 0s - loss: 0.2396 - accuracy: 0.9429 - val_loss: 0.1630 - val_accuracy: 0.9619
Epoch 6/20
 - 0s - loss: 0.2393 - accuracy: 0.9413 - val_loss: 0.1633 - val_accuracy: 0.9619
Epoch 7/20
 - 0s - loss: 0.2393 - accuracy: 0.9455 - val_loss: 0.1629 - val_accuracy: 0.9619
Epoch 8/20
 - 0s - loss: 0.2391 - accuracy: 0.9423 - val_loss: 0.1633 - val_accuracy: 0.9714
Epoch 9/20
 - 0s - loss: 0.2389 - accuracy: 0.9423 - val_loss: 0.1629 - val_accuracy: 0.9619
Epoch 10/20
 - 0s - loss: 0.2387 - accuracy: 0.9439 - val_loss: 0.1631 - val_accuracy: 0.9714
Epoch 11/20
 - 0s - lo

## Step-5: Make Predictions

### Create random test data

In [44]:
test_samples = []
test_labels = []

# Creating Dataset
for i in range(10):
    #The 5% of younger individuals who did experience side effects.
    #Random ages 13~65 years
    random_younger = np.random.randint(13, 64)
    test_samples.append(random_younger)
    test_labels.append(1)
    
    # The 5% of older individuals who did not experience side effects.
    #Random ages 65~100 years
    random_older = np.random.randint(65, 100)
    test_samples.append(random_older)
    test_labels.append(0)

for i in range(200):
    #The 5% of younger individuals who didnot experience side effects.
    #Random ages 13~65 years
    random_younger = np.random.randint(13, 64)
    test_samples.append(random_younger)
    test_labels.append(0)
    
    # The 5% of older individuals who did experience side effects.
    #Random ages 65~100 years
    random_older = np.random.randint(65, 100)
    test_samples.append(random_older)
    test_labels.append(1)

In [46]:
#shuffles the data
test_labels = np.array(test_labels)
test_samples = np.array(test_samples)

### Scaled the test data

In [47]:
scaler = MinMaxScaler(feature_range=(0,1))
scaled_test_samples = scaler.fit_transform(test_samples.reshape(-1,1))

In [48]:
#first 10 data
scaled_test_samples[:10]

array([[0.27906977],
       [1.        ],
       [0.30232558],
       [0.6627907 ],
       [0.48837209],
       [0.65116279],
       [0.05813953],
       [0.95348837],
       [0.58139535],
       [0.62790698]])

### Predictions

In [50]:
predictions = model.predict(scaled_test_samples, batch_size=10, verbose=0)

In [53]:
#tuple of predictions percentage
predictions[:10]

array([[0.96701425, 0.03298572],
       [0.01574942, 0.98425055],
       [0.96642345, 0.0335765 ],
       [0.14601175, 0.8539883 ],
       [0.8799175 , 0.12008253],
       [0.15745294, 0.8425471 ],
       [0.9693015 , 0.03069839],
       [0.02170351, 0.9782965 ],
       [0.48756957, 0.5124304 ],
       [0.23103535, 0.7689647 ]], dtype=float32)

In [54]:
rounded_predictions = model.predict_classes(scaled_test_samples, batch_size=10, verbose=0)

In [55]:
# Rounded predtions values
rounded_predictions[:10]

array([0, 1, 0, 1, 0, 1, 0, 1, 1, 1], dtype=int64)

## Step-6: Create  confusion matrix for predictions model

In [56]:
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
import itertools

%matplotlib inline

In [58]:
cm = confusion_matrix(test_labels, rounded_predictions)

In [61]:
cm

array([[198,  12],
       [  9, 201]], dtype=int64)

## Step-7: Save and Load model

### 1.  model.save()

In [62]:
model.save('medical_trial_model.h5')

In [63]:
from keras.models import load_model

In [64]:
new_model = load_model('medical_trial_model.h5')

In [65]:
new_model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_3 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_4 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


In [70]:
#new_model.get_weights()
new_model.optimizer

### 2. model.to_jeson[ ]
if you want to save the architecture of a model and not its weight or its training configurations, Use the following function to save the architecture only.

In [75]:
#save as JSON
json_string = model.to_json()

In [76]:
json_string

'{"class_name": "Sequential", "config": {"name": "sequential_2", "layers": [{"class_name": "Dense", "config": {"name": "dense_2", "trainable": true, "batch_input_shape": [null, 1], "dtype": "float32", "units": 16, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"scale": 1.0, "mode": "fan_avg", "distribution": "uniform", "seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "activity_regularizer": null, "kernel_constraint": null, "bias_constraint": null}}, {"class_name": "Dense", "config": {"name": "dense_3", "trainable": true, "dtype": "float32", "units": 32, "activation": "relu", "use_bias": true, "kernel_initializer": {"class_name": "VarianceScaling", "config": {"scale": 1.0, "mode": "fan_avg", "distribution": "uniform", "seed": null}}, "bias_initializer": {"class_name": "Zeros", "config": {}}, "kernel_regularizer": null, "bias_regularizer": null, "act

In [77]:
# model reconstruction from JSON:
from keras.models import model_from_json
model_architecture = model_from_json(json_string)

In [78]:
model_architecture.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_3 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_4 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________


### 3. model.save_weight( )
If you only need to save the weights of a model, Use the following function save the weights only.

In [79]:
model.save_weights('my_model_weights.h5')

In [80]:
model2 = Sequential([
    Dense(16, input_shape=(1,), activation='relu'),
    Dense(32, activation='relu'),
    Dense(2, activation='softmax')
])

In [81]:
model2.load_weights('my_model_weights.h5')

In [83]:
#model2.get_weights()

In [84]:
model2.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 16)                32        
_________________________________________________________________
dense_6 (Dense)              (None, 32)                544       
_________________________________________________________________
dense_7 (Dense)              (None, 2)                 66        
Total params: 642
Trainable params: 642
Non-trainable params: 0
_________________________________________________________________
